### ISSUE TITLE
Apache Ivy support?

### ISSUE THREAD

**Issue by pli2019** [cedx/setup-ant#1]
Hi, 

Does setup-ant support apache Ivy?  I want to use Ivy on my ant build action.

Thanks

**Comment by cedx** [comment]
Yes, Ivy is included with the Ant optional tasks:
https://cedx.github.io/setup-ant/#/usage/inputs

See, for example, this project:
https://github.com/cedx/akismet.java

There is the usual `ivy.xml` file declaring your dependencies, and the `optional-tasks` input is enabled in the workflow file:
https://github.com/cedx/akismet.java/blob/main/.github/workflows/main.yaml#L14
https://github.com/cedx/akismet.java/blob/main/build.xml#L55
