### ISSUE TITLE
Failed after some time with "read ECONNRESET"

### ISSUE THREAD

**Issue by super-brian** [cedx/setup-ant#2]
This action worked great on GitHub native runners (windows), but not on Self-hosted runners (windows).
Is it because of company policy or could you let me know how to run with more security?

By the way, 'setup-java' doesn't have v4 as shown on https://github.com/cedx/setup-ant/wiki/Matrix-setup

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 21
      - name: Setup ANT
        uses: cedx/setup-ant@v2

Run cedx/setup-ant@v2
read ECONNRESET
Waiting 14 seconds before trying again
read ECONNRESET
Waiting [16](https://github.3mhealth.com/fd/FluencyDirect/actions/runs/304942/job/881572#step:7:17) seconds before trying again
Error: Error: read ECONNRESET

**Comment by cedx** [comment]
> 'setup-java' doesn't have v4 as shown

See: https://github.com/actions/setup-java
The latest version is v4.2.1 and the "v4" tag exists. So the doc is up to date.

> Is it because of company policy or could you let me know how to run with more security?
Good question. I assume there is some sort of corporate or firewall policy that blocks the request.

The code of this action uses the standard `downloadTool()` API provided by GitHub in their `@actions/tool-cache` package (https://github.com/actions/toolkit/tree/main/packages/tool-cache).

It would probably be better to raise the issue on their project.

Is it possible to install this action directly in the environment where you use your self hosted runner, and run the test suite to see whether you still have this issue? (i.e. `git clone ...`, `npm install`, `npm test`)
