### ISSUE TITLE
Option `optional-tasks` fails with custom runners

### ISSUE THREAD

**Issue by super-brian** [cedx/setup-ant#3]
![image](https://github.com/user-attachments/assets/88cc6523-c09a-4516-96f4-181fff29bfca)
As seen above, it looks like 'ant' is tried but failed. Maybe Path issue?
I ran it on a windows runner.
Regardless, ant has been installed good, so no problem using it.

**Comment by cedx** [comment]
This error occurs when the `PATH` environment variable could not be set. Maybe something in your runner prevents the action from modifying this environment variable.

You could try to check if these 2 environment variables are OK:
- `ANT_HOME` (should print the path to Ant, that is `C:\actons-runner\[...]`)
- `PATH` (should include the path to the `bin` subfolder, that is `C:\actons-runner\[...]\bin`)

**Comment by super-brian** [comment]
After this action, all three of them look fine, but note that the error output is printed 'during' the action.
Maybe need to call 'refreshenv' or something like that inside the action so that env variables are reflected properly?

ANT_HOME=C:\actions-runner\_work\_tool\ant\1.10.15\x64
,,,
Path=C:\actions-runner\_work\_tool\ant\1.10.15\x64\bin;C:\actions-runner\_work\_tool\Java_Temurin-Hotspot_jdk\8.0.422-5\x64\bin;C:\Users\ContainerAdministrator\AppData\Roaming\Python\Python311\Scripts;C:\actions-runner\_work\_tool\Python\3.11.9\x64\Scripts;C:\actions-runner\_work\_tool\Python\3.11.9\x64;C:\Program Files\PowerShell\7;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\PowerShell\7\;C:\ProgramData\chocolatey\bin;C:\Users\ContainerAdministrator\AppData\Local\Microsoft\WindowsApps;C:\ProgramData\Chocolatey\bin;C:\Program Files\Git\cmd;;C:\Program Files\Git\bin;;C:\Program Files\Git\usr\bin;C:\Program Files\dotnet\;C:\Users\ContainerAdministrator\.dotnet\tools
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL

**Comment by cedx** [comment]
> the error output is printed 'during' the action.

Good catch! And I think I've found the root cause. When the `optional-tasks` option is enabled, the action will run the following command:

```
ant -buildfile fetch.xml -noinput -silent -Ddest=system
```

BUT: this command is run **before** the Ant environment variables are properly set.

It works on my machine because I already have a local Ant install declared in the `PATH`... and it turns out that GitHub hosted runners also have a local Ant install (see https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md#project-management). So it also works in GitHub CI with "standard" runners.

I'll get back to you as soon as I've published a fix.

**Comment by cedx** [comment]
@super-brian Can you check the `issue_3` branch?
(i.e. use `cedx/setup-ant@issue_3` instead of `cedx/setup-ant@v3` in your workflow file)

**Comment by super-brian** [comment]
OK, I will try now

**Comment by cedx** [comment]
It's going to be hard to debug: this error is triggered by Ant itself (but it confirms that Ant is now fully operational).

Ant can't seem to access the following URL:
`https://repository.jboss.org/nexus/content/groups/public/`

**Comment by cedx** [comment]
From my point of view, I consider this issue fixed: Ant nows as expected, despite the impossibility of downloading certain dependencies with your runner.
But feel free to reopen this issue (or create another one) if you think there's still something wrong with my code.
